### ISSUE TITLE
Add support for or switch to django-redis-cache, instead of django-redis

### ISSUE THREAD

**Issue by epicserve** [epicserve/django-cache-url#1]
If you have something like:

```python
import django_cache_url

print(django_cache_url.parse('redis://redis:6379/0'))
```

It would need to return:

```
{'BACKEND': 'django_redis.cache.RedisCache', 'LOCATION': 'redis:6379': OPTIONS: {'DB': 0}}
```

**Comment by epicserve** [comment]
We also need to look at all the different options and write better tests.

**Comment by epicserve** [comment]
I took a stab at this and started a pull request (#4). This makes it so both `django-redis` and `django-redis-cache` are supported with no breaking changes. You would just add `?lib=dj-redis-cache` to the `CACHE_URL` to use `django-redis-cache`.

All that needs to be done is update the documentation.

**Comment by incorvia** [comment]
If I understand this issue correctly since Heroku now requires SSL connections I can't connect to Redis via this project until this PR is merged. Is there anything holding it up?

**Comment by epicserve** [comment]
@incorvia,

I guess I waiting and hoping to get feedback on whether this is a good design or not and if others need or what this feature.
