### ISSUE TITLE
Support for PyMemcacheCache?

### ISSUE THREAD

**Issue by rain0r** [epicserve/django-cache-url#14]
Hi there,

it would be great if `django-cache-url` could support `PyMemcacheCache` too.

There is already a closed pull request  https://github.com/epicserve/django-cache-url/pull/12 which hasn't got merged. 

`MemcachedCache` is deprecated since version 3.2: https://docs.djangoproject.com/en/3.2/topics/cache/#filesystem-caching

**Comment by epicserve** [comment]
@rain0r,

Looks reasonable, but there needs to be tests. Want to add some?

**Comment by rain0r** [comment]
@epicserve 

Yes, I just opened the PR.
