### ISSUE TITLE
Wrong Redis backend name with Django 4.2

### ISSUE THREAD

**Issue by Real-Gecko** [epicserve/django-cache-url#31]
After upgrading to Django 4.2 backend name for Redis is incorrect.
I've created a sample project with:
```python
CACHES = {"default": {**django_cache_url.config(default="rediss://localhost:6379")}}
```
When I run shell and inspect settings I get different results for different Django versions:

django 3.2:
```shell
>>> settings.CACHES
{'default': {'BACKEND': 'django_redis.cache.RedisCache', 'LOCATION': 'rediss://loca
lhost:6379/0'}}
```

django 4.2:
```shell
>>> settings.CACHES
{'default': {'BACKEND': 'django.core.cache.backends.redis.RedisCache', 'LOCATION': 
'rediss://localhost:6379/0'}}
```

**Comment by Real-Gecko** [comment]
Sample project
https://github.com/Real-Gecko/django-cache-url-issuse-31

**Comment by epicserve** [comment]
That's the correct behavior and is intensional. If you're using Django >= 4, you don't need this library, but if you are still using it, it returns the built-in backend as designed.

**Comment by Real-Gecko** [comment]
Thanks for advice!
